# Generated by Django 3.0.7 on 2020-06-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('vendor', models.CharField(max_length=200)),
            ],
        ),
    ]
